from pathlib import Path


def replace_all(path: str, replacements: dict[str, str]) -> None:
    p = Path(path)
    text = p.read_text()
    for old, new in replacements.items():
        if old not in text:
            raise SystemExit(f"{path}: missing expected text: {old}")
        text = text.replace(old, new)
    p.write_text(text)


# Chat attachment / Codex entry point
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/ai/FilesPicker.kt",
    {
        'title = { Text("Reset Codex session?") }': 'title = { Text("Codex セッションをリセットしますか？") }',
        'text = { Text("Continuity with the current Codex thread will be lost. The next Send will create a new thread.") }': 'text = { Text("現在の Codex スレッドとの継続性が失われます。次回の送信時に新しいスレッドが作成されます。") }',
        '{ Text("Reset") }': '{ Text("リセット") }',
        '{ Text("Cancel") }': '{ Text("キャンセル") }',
        'assistant.workspaceId == null -> "Select a workspace before enabling Codex App Server"': 'assistant.workspaceId == null -> "Codex App Server を有効にする前にワークスペースを選択してください"',
        'selectedWorkspace == null -> "The selected workspace is unavailable"': 'selectedWorkspace == null -> "選択したワークスペースを利用できません"',
        'selectedWorkspace.shellStatus != WorkspaceShellStatus.READY.name -> "The workspace shell must be READY"': 'selectedWorkspace.shellStatus != WorkspaceShellStatus.READY.name -> "ワークスペースのシェルが READY である必要があります"',
        'else -> "Uses an App Server-managed thread; the normal provider model is not used"': 'else -> "App Server が管理するスレッドを使用します。通常のプロバイダーモデルは使用されません"',
        'headlineContent = { Text("Codex controls") }': 'headlineContent = { Text("Codex 設定") }',
        'Text("Connection, Account, Codex Skills, Codex MCP, and safety")': 'Text("接続、アカウント、Codex Skills、Codex MCP、安全性などを設定します")',
        '{ Text("Reset Codex session") }': '{ Text("Codex セッションをリセット") }',
    },
)

# Compact safety banner shown in the attachment sheet
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexSafetyPreferencePolicy.kt",
    {
        '"Full access".takeIf': '"フルアクセス".takeIf',
        '"No approvals".takeIf': '"承認なし".takeIf',
        'return "Server safety setting · Reset clears sticky overrides"': 'return "サーバーの安全設定 · リセットで以前の上書きを解除"',
    },
)

# Account card
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexAccountCard.kt",
    {
        'listOf("Waiting for ChatGPT sign-in")': 'listOf("ChatGPT へのサインインを待機中")',
        'listOf("Account status unavailable")': 'listOf("アカウント状態を取得できません")',
        'add("Signed in with ChatGPT")': 'add("ChatGPT でサインイン済み")',
        'listOf("Authenticated account")': 'listOf("認証済みアカウント")',
        'listOf("ChatGPT sign-in required")': 'listOf("ChatGPT へのサインインが必要です")',
        'listOf("No OpenAI sign-in required")': 'listOf("OpenAI へのサインインは不要です")',
        'Text("Codex account")': 'Text("Codex アカウント")',
        'Text("Cancel")': 'Text("キャンセル")',
        'Text("Sign in with ChatGPT")': 'Text("ChatGPT でサインイン")',
        'Text("Refresh")': 'Text("更新")',
        'Text("Log out")': 'Text("ログアウト")',
    },
)

# Approval UI
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexApprovalCards.kt",
    {
        'ApprovalSurface("Command approval"': 'ApprovalSurface("コマンドの承認"',
        'LabeledPlainText("Reason"': 'LabeledPlainText("理由"',
        'Text("Network access requested"': 'Text("ネットワークアクセスが要求されています"',
        'LabeledPlainText("Host"': 'LabeledPlainText("ホスト"',
        'LabeledPlainText("Protocol"': 'LabeledPlainText("プロトコル"',
        'LabeledPlainText("Command"': 'LabeledPlainText("コマンド"',
        'LabeledPlainText("Working directory"': 'LabeledPlainText("作業ディレクトリ"',
        'LabeledPlainText("Action"': 'LabeledPlainText("操作"',
        'LabeledPlainText("Environment"': 'LabeledPlainText("環境"',
        'ApprovalSurface("File-change approval"': 'ApprovalSurface("ファイル変更の承認"',
        'LabeledPlainText("Requested grant root"': 'LabeledPlainText("要求された許可ルート"',
        'Text("Change preview unavailable. Approval is disabled for your safety."': 'Text("変更内容のプレビューを取得できません。安全のため承認は無効になっています。"',
        'Text("Approve once")': 'Text("今回のみ承認")',
        'Text("Approve for session")': 'Text("このセッションで承認")',
        'Text("Decline rejects this action and lets the turn continue. Cancel turn rejects it and stops the turn."': 'Text("「拒否」はこの操作だけを拒否して処理を続行します。「ターンをキャンセル」は拒否したうえで現在のターンを停止します。"',
        'Text("Decline")': 'Text("拒否")',
        'Text("Cancel turn")': 'Text("ターンをキャンセル")',
        '"Read: ${action.path}"': '"読み取り: ${action.path}"',
        '"List files: $it"': '"ファイル一覧: $it"',
        '"List files"': '"ファイル一覧"',
        '"Search: ${action.query} in ${action.path}"': '"検索: ${action.path} 内で ${action.query}"',
        '"Search: ${action.query}"': '"検索: ${action.query}"',
        '"Search in: ${action.path}"': '"検索場所: ${action.path}"',
        'else -> "Search"': 'else -> "検索"',
        '"Command: ${action.command}"': '"コマンド: ${action.command}"',
        '"Unknown command action"': '"不明なコマンド操作"',
    },
)

# Execution / diff cards
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexExecutionCards.kt",
    {
        '" · exit $it"': '" · 終了コード $it"',
        'CollapsibleText(it, "Output"': 'CollapsibleText(it, "出力"',
        'is CodexAppServerPatchChangeKind.Add -> "Add"': 'is CodexAppServerPatchChangeKind.Add -> "追加"',
        'is CodexAppServerPatchChangeKind.Delete -> "Delete"': 'is CodexAppServerPatchChangeKind.Delete -> "削除"',
        'is CodexAppServerPatchChangeKind.Update -> "Update${kind.movePath?.let { " → $it" } ?: ""}"': 'is CodexAppServerPatchChangeKind.Update -> "更新${kind.movePath?.let { " → $it" } ?: ""}"',
        'CollapsibleText(change.diff, "Diff"': 'CollapsibleText(change.diff, "差分"',
        'Text("Turn diff"': 'Text("ターンの差分"',
        'if (expanded) "Hide $label" else "Show $label (${text.length} characters)"': 'if (expanded) "$label を隠す" else "$label を表示（${text.length}文字）"',
    },
)

# Usage/status helper
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexUsageFormatting.kt",
    {
        '"${durationMs / 60_000} min ${(durationMs % 60_000) / 1_000} s"': '"${durationMs / 60_000}分 ${(durationMs % 60_000) / 1_000}秒"',
        '"Completed"': '"完了"',
        '"Interrupted"': '"中断"',
        '"Failed"': '"失敗"',
        '"In progress"': '"実行中"',
        'null -> "Codex error"': 'null -> "Codex エラー"',
        'is CodexAppServerErrorInfo.Unknown -> "Other Codex error"': 'is CodexAppServerErrorInfo.Unknown -> "その他の Codex エラー"',
    },
)

# Model composer fallback labels
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexModelPreferencePolicy.kt",
    {
        'if (it == "fast") "Fast" else it, "Legacy service tier"': 'if (it == "fast") "高速" else it, "従来のサービスタイア"',
        'assistant.codexModel ?: "server default"': 'assistant.codexModel ?: "サーバー既定"',
        'if (saved == "default") "Default"': 'if (saved == "default") "既定"',
    },
)

# Main Codex control center. These strings are RikkaHub-owned UI, not server-returned content.
replace_all(
    "app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexControlSheet.kt",
    {
        'item { Text("Codex Control Center"': 'item { Text("Codex コントロールセンター"',
        'Section("Thread history")': 'Section("スレッド履歴")',
        'Text("Back to history")': 'Text("履歴に戻る")',
        '"Untitled thread"': '"無題のスレッド"',
        'Text("Thread ID: ${thread.id}"': 'Text("スレッド ID: ${thread.id}"',
        'Text("Model provider: $it")': 'Text("モデルプロバイダー: $it")',
        'Text("Status: ${it.wireValue}")': 'Text("状態: ${it.wireValue}")',
        'Text("Recency: $it")': 'Text("最終利用: $it")',
        'Text("Updated: $it")': 'Text("更新日時: $it")',
        'Text("Turn ${historyTurn.turn.id}"': 'Text("ターン ${historyTurn.turn.id}"',
        'Text("Browse persisted App Server threads without switching this conversation.")': 'Text("この会話を切り替えずに、保存済みの App Server スレッドを参照できます。")',
        'label = { Text("Search") }': 'label = { Text("検索") }',
        '"Active filter: ${history.searchTerm}"': '"適用中の絞り込み: ${history.searchTerm}"',
        '"Refresh current results" else "Load history"': '"現在の結果を更新" else "履歴を読み込む"',
        '"Clear search" else "Search"': '"検索をクリア" else "検索"',
        'Text("Current"': 'Text("現在"',
        'Text("View details")': 'Text("詳細を見る")',
        'Text("Load more")': 'Text("さらに読み込む")',
        'Section("Usage & status")': 'Section("使用量と状態")',
        'Text("No token usage reported yet")': 'Text("トークン使用量はまだ報告されていません")',
        'Text("Current context"': 'Text("現在のコンテキスト"',
        'Text("Context window: Not reported")': 'Text("コンテキストウィンドウ: 未報告")',
        'Text("Session total: ${formatTokenCount(usage.total.totalTokens)} tokens")': 'Text("セッション合計: ${formatTokenCount(usage.total.totalTokens)} トークン")',
        'Text("Latest usage breakdown"': 'Text("直近の使用量内訳"',
        'Text("Input: ${formatTokenCount(usage.last.inputTokens)}")': 'Text("入力: ${formatTokenCount(usage.last.inputTokens)}")',
        'Text("Cached input: ${formatTokenCount(usage.last.cachedInputTokens)}")': 'Text("キャッシュ済み入力: ${formatTokenCount(usage.last.cachedInputTokens)}")',
        'Text("Cache write input: ${formatTokenCount(it)}")': 'Text("キャッシュ書き込み入力: ${formatTokenCount(it)}")',
        'Text("Output: ${formatTokenCount(usage.last.outputTokens)}")': 'Text("出力: ${formatTokenCount(usage.last.outputTokens)}")',
        'Text("Reasoning output: ${formatTokenCount(usage.last.reasoningOutputTokens)}")': 'Text("推論出力: ${formatTokenCount(usage.last.reasoningOutputTokens)}")',
        'Text("Usage warning: $it"': 'Text("使用量の警告: $it"',
        'Section("Configuration & policy")': 'Section("構成とポリシー")',
        'Text("These are App Server base and managed settings. RikkaHub thread and turn overrides may differ.")': 'Text("ここには App Server の基本設定と管理ポリシーを表示します。RikkaHub 側のスレッド・ターン上書き設定とは異なる場合があります。")',
        '"Load configuration" else "Refresh diagnostics"': '"構成を読み込む" else "診断情報を更新"',
        'Text("Configuration: $it"': 'Text("構成: $it"',
        'Text("Managed requirements: $it"': 'Text("管理ポリシー: $it"',
        '"Base App Server configuration · Thread-agnostic configuration" else "Base App Server configuration"': '"App Server 基本構成 · スレッド非依存" else "App Server 基本構成"',
        'configRow("Model",': 'configRow("モデル",',
        'configRow("Model provider",': 'configRow("モデルプロバイダー",',
        'configRow("Model context window",': 'configRow("モデルのコンテキストウィンドウ",',
        'configRow("Auto compact limit",': 'configRow("自動圧縮の上限",',
        'configRow("Sandbox default",': 'configRow("サンドボックス既定値",',
        '"${it.wireValue} (unknown)"': '"${it.wireValue}（不明）"',
        'configRow("Workspace-write network access",': 'configRow("ワークスペース書き込み時のネットワークアクセス",',
        'Text("Writable roots: $it")': 'Text("書き込み可能ルート: $it")',
        'configRow("Web search",': 'configRow("Web 検索",',
        'configRow("Reasoning effort",': 'configRow("推論強度",',
        'configRow("Reasoning summary",': 'configRow("推論要約",',
        'configRow("Verbosity",': 'configRow("回答の詳しさ",',
        'configRow("Service tier",': 'configRow("サービスタイア",',
        'configRow("Analytics",': 'configRow("分析データ",',
        'Text("Managed requirements"': 'Text("管理ポリシー"',
        'Text("Allowed sandbox modes: "': 'Text("許可されているサンドボックス: "',
        'Text("Allowed web search: "': 'Text("許可されている Web 検索: "',
        'Text("Managed new-thread model: $it")': 'Text("新規スレッドで指定されるモデル: $it")',
        'Text("Managed new-thread effort: $it")': 'Text("新規スレッドで指定される推論強度: $it")',
        'Text("Managed new-thread service tier: $it")': 'Text("新規スレッドで指定されるサービスタイア: $it")',
        '"$feature = required ${if (required) "enabled" else "disabled"}"': '"$feature = ${if (required) "有効化必須" else "無効化必須"}"',
        'Text("No managed requirements reported")': 'Text("管理ポリシーは報告されていません")',
        'Section("Code review")': 'Section("コードレビュー")',
        'Text("Run a native inline review on this conversation\'s bound thread.")': 'Text("この会話に紐づくスレッド上で Codex のネイティブレビューを実行します。")',
        'var reviewKind by remember { mutableStateOf("Working tree") }': 'var reviewKind by remember { mutableStateOf("Working tree") }',
        'listOf("Working tree", "Base branch", "Commit", "Custom").forEach { kind ->': 'listOf("Working tree", "Base branch", "Commit", "Custom").forEach { kind ->\n                    val kindLabel = when (kind) { "Working tree" -> "作業ツリー"; "Base branch" -> "ベースブランチ"; "Commit" -> "コミット"; else -> "カスタム" }',
        'Text((if (reviewKind == kind) "✓ " else "") + kind)': 'Text((if (reviewKind == kind) "✓ " else "") + kindLabel)',
        'label = { Text("Branch") }': 'label = { Text("ブランチ") }',
        'label = { Text("Commit SHA") }': 'label = { Text("コミット SHA") }',
        'label = { Text("Title (optional)") }': 'label = { Text("タイトル（任意）") }',
        'label = { Text("Review instructions") }': 'label = { Text("レビュー指示") }',
        'Text("Review in progress · ${review.targetSummary.orEmpty()}")': 'Text("レビュー実行中 · ${review.targetSummary.orEmpty()}")',
        'Text("Stop review")': 'Text("レビューを停止")',
        'Text("Start review")': 'Text("レビューを開始")',
        'Section("Safety & permissions")': 'Section("安全性と権限")',
        'Text("Sandbox"': 'Text("サンドボックス"',
        'Text("Server setting omits the override. On an existing thread a previous override may be sticky; Reset is required to return completely to server configuration.")': 'Text("「サーバー設定」はRikkaHub側から値を上書きしません。既存スレッドでは以前の上書きが残る場合があるため、完全にサーバー設定へ戻すにはセッションのリセットが必要です。")',
        'null to "Server setting", "read-only" to "Read only", "workspace-write" to "Workspace write", "danger-full-access" to "Full access"': 'null to "サーバー設定", "read-only" to "読み取り専用", "workspace-write" to "ワークスペース書き込み", "danger-full-access" to "フルアクセス"',
        '"Codex can read project files but writes are restricted."': '"Codex はプロジェクトファイルを読み取れますが、書き込みは制限されます。"',
        '"Codex can modify files allowed by the workspace sandbox."': '"Codex はワークスペースのサンドボックスで許可されたファイルを変更できます。"',
        '"Removes Codex sandbox restrictions for the environment available to the App Server."': '"App Server から利用できる環境に対する Codex のサンドボックス制限を解除します。"',
        '"The App Server setting is used when no explicit override is selected."': '"明示的な上書きを選択しない場合は App Server 側の設定を使用します。"',
        'Text("Unsupported saved sandbox preference': 'Text("未対応の保存済みサンドボックス設定',
        'is preserved and will not be sent."': 'は保持されますが、App Server には送信されません。"',
        'Text("Approval"': 'Text("承認ポリシー"',
        'null to "Server setting", "untrusted" to "Untrusted", "on-request" to "On request", "never" to "Never"': 'null to "サーバー設定", "untrusted" to "信頼済み操作のみ自動承認", "on-request" to "必要時に確認", "never" to "承認を求めない"',
        '"Only known-safe read-only commands are automatically approved; other operations may request approval."': '"安全と判定された読み取り専用コマンドだけを自動承認し、それ以外の操作では承認を求める場合があります。"',
        '"Codex decides when it needs to ask for approval."': '"Codex が必要と判断したときに承認を求めます。"',
        '"Codex does not ask for approval; blocked operations fail instead. This does not itself mean Full access."': '"Codex は承認を求めません。ポリシーやサンドボックスで禁止された操作は、そのまま失敗します。これだけでフルアクセスになるわけではありません。"',
        '"Server approval policy is used when no explicit override is selected."': '"明示的な上書きを選択しない場合はサーバー側の承認ポリシーを使用します。"',
        'Text("Unsupported saved approval preference': 'Text("未対応の保存済み承認設定',
        'Section("Model & behavior")': 'Section("モデルと動作")',
        'Text("Codex model"': 'Text("Codex モデル"',
        'Text("The App Server catalog is authoritative. Changes apply from the next Codex turn.")': 'Text("App Server のモデル一覧が基準です。変更は次の Codex ターンから適用されます。")',
        '"Load models" else "Refresh models"': '"モデルを読み込む" else "モデル一覧を更新"',
        '"Saved Codex model': '"保存済みの Codex モデル',
        'is no longer available. Select another model explicitly; RikkaHub will not silently replace it."': 'は現在利用できません。別のモデルを明示的に選択してください。RikkaHub が自動で置き換えることはありません。"',
        'Text("Current preference: server default. After an explicit selection, a concrete catalog model is saved.")': 'Text("現在の設定: サーバー既定。モデルを明示的に選択すると、そのモデルが保存されます。")',
        '" · Default"': '" · 既定"',
        'prefix = "Inputs: "': 'prefix = "入力: "',
        '?: "Inputs: not reported"': '?: "入力: 未報告"',
        'Text("Effort: "': 'Text("推論強度: "',
        'Text("This catalog entry has invalid reasoning-effort metadata."': 'Text("このモデルの推論強度メタデータが不正です。"',
        'Text("This model does not advertise personality support")': 'Text("このモデルはパーソナリティ設定への対応を報告していません")',
        'Text(if (assistant.codexModel == model.model) "Selected" else "Select")': 'Text(if (assistant.codexModel == model.model) "選択中" else "選択")',
        'Text("Service tier"': 'Text("サービスタイア"',
        'Text("Server setting omits the override. On an existing thread, the server-side tier may remain sticky. Default explicitly requests the default tier on the next turn.")': 'Text("「サーバー設定」はRikkaHub側から値を上書きしません。既存スレッドでは以前のサービスタイアが残る場合があります。「既定」を選ぶと次のターンで既定タ���イアを明示的に要求します。")',
        '+ "Server setting"': '+ "サーバー設定"',
        '+ "Default"': '+ "既定"',
        'Text("Catalog default: $label")': 'Text("カタログ上の既定値: $label")',
        'Text("Tier support not confirmed in the current model catalog")': 'Text("現在のモデル一覧ではサービスタイア対応を確認できません")',
        'Text("Tier support not reported by this App Server; the saved exact tier will be preserved")': 'Text("この App Server はサービスタイア対応を報告していません。保存済みの指定値は保持されます")',
        'Text("Tier is not supported by the selected Codex model"': 'Text("選択した Codex モデルはこのサービスタイアに対応していません"',
        'Text("Reasoning summary")': 'Text("推論要約")',
        'Text("Personality")': 'Text("パーソナリティ")',
        'Section("Connection")': 'Section("接続")',
        'Text("Reconnect Codex")': 'Text("Codex に再接続")',
        'Section("Account")': 'Section("アカウント")',
        'Section("Codex Skills")': 'Section("Codex Skills")',
        '"${capabilities.skillGroups.sumOf { it.skills.size }} skills"': '"${capabilities.skillGroups.sumOf { it.skills.size }} 件のスキル"',
        ') { Text("Refresh") }': ') { Text("更新") }',
        'Text(if (skill.enabled) "Disable" else "Enable")': 'Text(if (skill.enabled) "無効化" else "有効化")',
        'Text("Use")': 'Text("使用")',
        'Text("Reload MCP")': 'Text("MCP を再読み込み")',
        '"${server.authStatus.wireValue} · ${server.tools.size} tools · ${server.resources.size} resources"': '"${server.authStatus.wireValue} · ツール ${server.tools.size}件 · リソース ${server.resources.size}件"',
        'Text("Sign in")': 'Text("サインイン")',
        '"Critical safety warning" else "Confirm safety setting"': '"重大な安全性の警告" else "安全設定の確認"',
        '"Full access + Never removes the normal sandbox restriction while also disabling approval prompts. Codex may modify data available in its execution environment without asking."': '"「フルアクセス」+「承認を求めない」は通常のサンドボックス制限を解除し、承認確認も無効にします。Codex は実行環境からアクセス可能なデータを確認なしで変更できる可能性があります。"',
        '"Sandbox restrictions are removed. Codex may modify data available inside its execution environment. Enable only when you intentionally want unrestricted execution."': '"サンドボックス制限が解除されます。Codex は実行環境内のデータを変更できる可能性があります。制限のない実行を意図している場合のみ有効にしてください。"',
        '"Approval prompts are disabled. Operations blocked by the sandbox or policy may fail rather than ask. This does not itself mean Full access."': '"承認確認が無効になります。サンドボックスやポリシーで禁止された操作は、確認を求めず失敗する場合があります。これだけでフルアクセスになるわけではありません。"',
        'Text("Confirm")': 'Text("確認")',
        'Text("Cancel")': 'Text("キャンセル")',
        'is CodexAppServerItemSnapshot.UserMessage -> {': 'is CodexAppServerItemSnapshot.UserMessage -> {',
        'ifBlank { "[empty message]" }': 'ifBlank { "[空のメッセージ]" }',
        '"User: $content"': '"ユーザー: $content"',
        'is CodexAppServerItemSnapshot.AgentMessage -> "Agent: ${item.text}"': 'is CodexAppServerItemSnapshot.AgentMessage -> "エージェント: ${item.text}"',
        'is CodexAppServerItemSnapshot.Reasoning -> "Reasoning: ${(item.summary + item.content).joinToString("\\n")}"': 'is CodexAppServerItemSnapshot.Reasoning -> "推論: ${(item.summary + item.content).joinToString("\\n")}"',
        'is CodexAppServerItemSnapshot.CommandExecution -> "Command: ${item.command}${item.aggregatedOutput?.let { "\\n$it" }.orEmpty()}"': 'is CodexAppServerItemSnapshot.CommandExecution -> "コマンド: ${item.command}${item.aggregatedOutput?.let { "\\n$it" }.orEmpty()}"',
        'is CodexAppServerItemSnapshot.FileChange -> "File changes: ${item.changes.size}"': 'is CodexAppServerItemSnapshot.FileChange -> "ファイル変更: ${item.changes.size}件"',
        'is CodexAppServerItemSnapshot.EnteredReviewMode -> "Entered review mode: ${item.review}"': 'is CodexAppServerItemSnapshot.EnteredReviewMode -> "レビューモード開始: ${item.review}"',
        'is CodexAppServerItemSnapshot.ExitedReviewMode -> "Exited review mode: ${item.review}"': 'is CodexAppServerItemSnapshot.ExitedReviewMode -> "レビューモード終了: ${item.review}"',
        'is CodexAppServerItemSnapshot.Other -> "${item.type} item"': 'is CodexAppServerItemSnapshot.Other -> "${item.type} アイテム"',
        'is CodexAppServerUserInput.Image -> "[Image]"': 'is CodexAppServerUserInput.Image -> "[画像]"',
        '"[Local image: ${input.path.substringAfterLast(\'/\').ifBlank { "image" }}]"': '"[ローカル画像: ${input.path.substringAfterLast(\'/\').ifBlank { "image" }}]"',
        'is CodexAppServerUserInput.Audio -> "[Audio]"': 'is CodexAppServerUserInput.Audio -> "[音声]"',
        '"[Local audio: ${input.path.substringAfterLast(\'/\').ifBlank { "audio" }}]"': '"[ローカル音声: ${input.path.substringAfterLast(\'/\').ifBlank { "audio" }}]"',
        'is CodexAppServerUserInput.Skill -> "[Skill: ${input.name}]"': 'is CodexAppServerUserInput.Skill -> "[スキル: ${input.name}]"',
        'CodexConversationUiState.Disabled -> "Disabled"': 'CodexConversationUiState.Disabled -> "無効"',
        'CodexConversationUiState.Disconnected -> if (bound) "Disconnected but bound" else "Send a Codex message first to create the conversation thread."': 'CodexConversationUiState.Disconnected -> if (bound) "切断されています（スレッド紐付けあり）" else "最初に Codex へメッセージを送信すると会話スレッドが作成されます。"',
        'CodexConversationUiState.Opening -> "Connecting"': 'CodexConversationUiState.Opening -> "接続中"',
        'is CodexConversationUiState.Ready -> "Connected"': 'is CodexConversationUiState.Ready -> "接続済み"',
        'is CodexConversationUiState.Running, is CodexConversationUiState.WaitingForApproval -> "Running"': 'is CodexConversationUiState.Running, is CodexConversationUiState.WaitingForApproval -> "実行中"',
        'is CodexConversationUiState.Terminal -> "Connected"': 'is CodexConversationUiState.Terminal -> "接続済み"',
        'is CodexConversationUiState.Failed -> "Failed: ${state.message}"': 'is CodexConversationUiState.Failed -> "失敗: ${state.message}"',
        'is CodexConversationUiState.StaleBinding -> "Failed: ${state.reason}"': 'is CodexConversationUiState.StaleBinding -> "失敗: ${state.reason}"',
        'is CodexConversationUiState.WorkspaceMismatch -> "Failed: workspace mismatch"': 'is CodexConversationUiState.WorkspaceMismatch -> "失敗: ワークスペースが一致しません"',
        'private fun Boolean.enabledLabel() = if (this) "Enabled" else "Disabled"': 'private fun Boolean.enabledLabel() = if (this) "有効" else "無効"',
        '"read-only" -> "Read only"': '"read-only" -> "読み取り専用"',
        '"workspace-write" -> "Workspace write"': '"workspace-write" -> "ワークスペース書き込み"',
        'else -> "Full access"': 'else -> "フルアクセス"',
        'return "Managed policy currently does not allow $label. The saved preference is unchanged; the App Server remains authoritative."': 'return "管理ポリシーでは現在「$label」は許可されていません。保存済み設定は変更せず、App Server 側のポリシーを優先します。"',
    },
)
