from pathlib import Path

p = Path("app/src/main/java/me/rerere/rikkahub/ui/components/codex/CodexControlSheet.kt")
text = p.read_text()


def one(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected exactly one match, found {count}: {old}")
    text = text.replace(old, new, 1)

one(
    '    val serviceTierModel = serviceTierCatalogModel(assistant.codexModel, capabilities.models)\n',
    '    val serviceTierModel = serviceTierCatalogModel(assistant.codexModel, capabilities.models)\n'
    '    val japanese = codexUiText("Completed") == "完了"\n',
)
one(
    '                        thread.cwd?.let { Text("CWD: ${it.substringAfterLast(\'/\').ifBlank { "/" }}", maxLines = 2, overflow = TextOverflow.Ellipsis) }',
    '                        thread.cwd?.let { Text((if (japanese) "作業ディレクトリ: " else "CWD: ") + it.substringAfterLast(\'/\').ifBlank { "/" }, maxLines = 2, overflow = TextOverflow.Ellipsis) }',
)
one(
    '                            Text("${historyTurn.turn.status.wireValue}${historyTurn.turn.durationMs?.let { " · ${it}ms" }.orEmpty()}")',
    '                            Text((if (japanese) localizedTurnWireStatus(historyTurn.turn.status.wireValue) else historyTurn.turn.status.wireValue) + historyTurn.turn.durationMs?.let { " · ${it}ms" }.orEmpty())',
)
one('                    Text(currentContextText(usage))', '                    Text(if (japanese) currentContextText(usage).replace(" tokens", " トークン") else currentContextText(usage))')
one('                    Text("Input: ${formatTokenCount(usage.last.inputTokens)}")', '                    Text((if (japanese) "入力: " else "Input: ") + formatTokenCount(usage.last.inputTokens))')
one('                    Text("Cached input: ${formatTokenCount(usage.last.cachedInputTokens)}")', '                    Text((if (japanese) "キャッシュ済み入力: " else "Cached input: ") + formatTokenCount(usage.last.cachedInputTokens))')
one('                    usage.last.cacheWriteInputTokens?.let { Text("Cache write input: ${formatTokenCount(it)}") }', '                    usage.last.cacheWriteInputTokens?.let { Text((if (japanese) "キャッシュ書き込み入力: " else "Cache write input: ") + formatTokenCount(it)) }')
one('                    Text("Output: ${formatTokenCount(usage.last.outputTokens)}")', '                    Text((if (japanese) "出力: " else "Output: ") + formatTokenCount(usage.last.outputTokens))')
one('                    Text("Reasoning output: ${formatTokenCount(usage.last.reasoningOutputTokens)}")', '                    Text((if (japanese) "推論出力: " else "Reasoning output: ") + formatTokenCount(usage.last.reasoningOutputTokens))')
one('                    Text(turnStatusText(turn), style = MaterialTheme.typography.titleMedium)', '                    Text(if (japanese) localizedTurnStatusSummary(turnStatusText(turn)) else turnStatusText(turn), style = MaterialTheme.typography.titleMedium)')
one('                        Text("${errorCategoryLabel(error.codexErrorInfo)}: ${error.message}", color = MaterialTheme.colorScheme.error)', '                        Text((if (japanese) localizedErrorCategory(errorCategoryLabel(error.codexErrorInfo)) else errorCategoryLabel(error.codexErrorInfo)) + ": ${error.message}", color = MaterialTheme.colorScheme.error)')
one('                    Text(if (config.threadAgnostic) "Base App Server configuration · Thread-agnostic configuration" else "Base App Server configuration", style = MaterialTheme.typography.titleMedium)', '                    Text(if (japanese) { if (config.threadAgnostic) "App Server 基本構成 · スレッド非依存" else "App Server 基本構成" } else { if (config.threadAgnostic) "Base App Server configuration · Thread-agnostic configuration" else "Base App Server configuration" }, style = MaterialTheme.typography.titleMedium)')
one('                    configRow(codexUiText("Sandbox default"), config.sandboxMode?.let { if (it.known) it.wireValue else "${it.wireValue} (unknown)" }, config, "sandbox_mode")', '                    configRow(codexUiText("Sandbox default"), config.sandboxMode?.let { if (it.known) it.wireValue else if (japanese) "${it.wireValue}（不明）" else "${it.wireValue} (unknown)" }, config, "sandbox_mode")')
one('                        requirements.allowedSandboxModes?.let { Text("Allowed sandbox modes: " + it.joinToString(" · ") { mode -> mode.wireValue }) }', '                        requirements.allowedSandboxModes?.let { Text((if (japanese) "許可されているサンドボックス: " else "Allowed sandbox modes: ") + it.joinToString(" · ") { mode -> mode.wireValue }) }')
one('                        requirements.allowedWebSearchModes?.let { Text("Allowed web search: " + it.joinToString(" · ")) }', '                        requirements.allowedWebSearchModes?.let { Text((if (japanese) "許可されている Web 検索: " else "Allowed web search: ") + it.joinToString(" · ")) }')
one('                        requirements.newThread?.model?.let { Text("Managed new-thread model: $it") }', '                        requirements.newThread?.model?.let { Text((if (japanese) "新規スレッドで指定されるモデル: " else "Managed new-thread model: ") + it) }')
one('                        requirements.newThread?.modelReasoningEffort?.let { Text("Managed new-thread effort: $it") }', '                        requirements.newThread?.modelReasoningEffort?.let { Text((if (japanese) "新規スレッドで指定される推論強度: " else "Managed new-thread effort: ") + it) }')
one('                        requirements.newThread?.serviceTier?.let { Text("Managed new-thread service tier: $it") }', '                        requirements.newThread?.serviceTier?.let { Text((if (japanese) "新規スレッドで指定されるサービスタイア: " else "Managed new-thread service tier: ") + it) }')
one('                        requirements.featureRequirements?.forEach { (feature, required) -> Text("$feature = required ${if (required) "enabled" else "disabled"}") }', '                        requirements.featureRequirements?.forEach { (feature, required) -> Text(if (japanese) "$feature = ${if (required) "有効化必須" else "無効化必須"}" else "$feature = required ${if (required) "enabled" else "disabled"}") }')
one('                Text("Server setting omits the override. On an existing thread a previous override may be sticky; Reset is required to return completely to server configuration.")', '                Text(if (japanese) "「サーバー設定」はRikkaHub側から値を上書きしません。既存スレッドでは以前の上書きが残る場合があるため、完全にサーバー設定へ戻すにはCodexセッションのリセットが必要です。" else "Server setting omits the override. On an existing thread a previous override may be sticky; Reset is required to return completely to server configuration.")')
one('                if (!codexSandboxKnown(assistant.codexSandboxMode)) Text("Unsupported saved sandbox preference \'${assistant.codexSandboxMode}\' is preserved and will not be sent.", color = MaterialTheme.colorScheme.error)', '                if (!codexSandboxKnown(assistant.codexSandboxMode)) Text(if (japanese) "未対応の保存済みサンドボックス設定 \'${assistant.codexSandboxMode}\' は保持されますが、App Serverには送信されません。" else "Unsupported saved sandbox preference \'${assistant.codexSandboxMode}\' is preserved and will not be sent.", color = MaterialTheme.colorScheme.error)')
one('                    Text(it, color = MaterialTheme.colorScheme.error)', '                    Text(if (japanese) "管理ポリシーでは現在このサンドボックス設定を許可していません。保存済み設定は変更せず、App Server側のポリシーを優先します。" else it, color = MaterialTheme.colorScheme.error)')
one('                if (!codexApprovalKnown(assistant.codexApprovalPolicy)) Text("Unsupported saved approval preference \'${assistant.codexApprovalPolicy}\' is preserved and will not be sent.", color = MaterialTheme.colorScheme.error)', '                if (!codexApprovalKnown(assistant.codexApprovalPolicy)) Text(if (japanese) "未対応の保存済み承認設定 \'${assistant.codexApprovalPolicy}\' は保持されますが、App Serverには送信されません。" else "Unsupported saved approval preference \'${assistant.codexApprovalPolicy}\' is preserved and will not be sent.", color = MaterialTheme.colorScheme.error)')
one('                    Text(if (capabilities.models.isEmpty()) "Load models" else "Refresh models")', '                    Text(codexUiText(if (capabilities.models.isEmpty()) "Load models" else "Refresh models"))')
one('                        "Saved Codex model \'${assistant.codexModel}\' is no longer available. Select another model explicitly; RikkaHub will not silently replace it.",', '                        if (japanese) "保存済みの Codex モデル \'${assistant.codexModel}\' は現在利用できません。別のモデルを明示的に選択してください。RikkaHubが自動で置き換えることはありません。" else "Saved Codex model \'${assistant.codexModel}\' is no longer available. Select another model explicitly; RikkaHub will not silently replace it.",')
one('                    Text("Current preference: server default. After an explicit selection, a concrete catalog model is saved.")', '                    Text(if (japanese) "現在の設定: サーバー既定。モデルを明示的に選択すると、そのモデルが保存されます。" else "Current preference: server default. After an explicit selection, a concrete catalog model is saved.")')
one('                        model.displayName + if (model.isDefault) " · Default" else "",', '                        model.displayName + if (model.isDefault) { if (japanese) " · 既定" else " · Default" } else "",')
one('                            model.inputModalities?.joinToString(" · ", prefix = "Inputs: ")\n                                ?: "Inputs: not reported",', '                            model.inputModalities?.joinToString(" · ", prefix = if (japanese) "入力: " else "Inputs: ")\n                                ?: if (japanese) "入力: 未報告" else "Inputs: not reported",')
one('                            Text("Effort: " + advertisedEfforts.joinToString(" · "), maxLines = 2, overflow = TextOverflow.Ellipsis)', '                            Text((if (japanese) "推論強度: " else "Effort: ") + advertisedEfforts.joinToString(" · "), maxLines = 2, overflow = TextOverflow.Ellipsis)')
one('                            Text("This catalog entry has invalid reasoning-effort metadata.", color = MaterialTheme.colorScheme.error)', '                            Text(if (japanese) "このモデルの推論強度メタデータが不正です。" else "This catalog entry has invalid reasoning-effort metadata.", color = MaterialTheme.colorScheme.error)')
one('                        if (!model.supportsPersonality) Text("This model does not advertise personality support")', '                        if (!model.supportsPersonality) Text(if (japanese) "このモデルはパーソナリティ設定への対応を報告していません" else "This model does not advertise personality support")')
one('            Text("Server setting omits the override. On an existing thread, the server-side tier may remain sticky. Default explicitly requests the default tier on the next turn.")', '            Text(if (japanese) "「サーバー設定」はRikkaHub側から値を上書きしません。既存スレッドでは以前のサービスタイアが残る場合があります。「既定」は次のターンで既定タ���イアを明示的に要求します。" else "Server setting omits the override. On an existing thread, the server-side tier may remain sticky. Default explicitly requests the default tier on the next turn.")')
one('                    Text("Catalog default: $label")', '                    Text((if (japanese) "カタログ上の既定値: " else "Catalog default: ") + label)')
one('                    serviceTierModel == null -> Text("Tier support not confirmed in the current model catalog")', '                    serviceTierModel == null -> Text(if (japanese) "現在のモデル一覧ではサービスタイア対応を確認できません" else "Tier support not confirmed in the current model catalog")')
one('                        Text("Tier support not reported by this App Server; the saved exact tier will be preserved")', '                        Text(if (japanese) "この App Server はサービスタイア対応を報告していません。保存済みの指定値は保持されます" else "Tier support not reported by this App Server; the saved exact tier will be preserved")')
one('                        Text("Tier is not supported by the selected Codex model", color = MaterialTheme.colorScheme.error)', '                        Text(if (japanese) "選択した Codex モデルはこのサービスタイアに対応していません" else "Tier is not supported by the selected Codex model", color = MaterialTheme.colorScheme.error)')
one('                    Text("This model does not advertise personality support")', '                    Text(if (japanese) "このモデルはパーソナリティ設定への対応を報告していません" else "This model does not advertise personality support")')
one('                supportingContent = { Text("${server.authStatus.wireValue} · ${server.tools.size} tools · ${server.resources.size} resources") },', '                supportingContent = { Text(if (japanese) "${server.authStatus.wireValue} · ツール ${server.tools.size}件 · リソース ${server.resources.size}件" else "${server.authStatus.wireValue} · ${server.tools.size} tools · ${server.resources.size} resources") },')
one('            title = { Text(if (kind == CodexSafetyConfirmation.CRITICAL) "Critical safety warning" else "Confirm safety setting") },', '            title = { Text(codexUiText(if (kind == CodexSafetyConfirmation.CRITICAL) "Critical safety warning" else "Confirm safety setting")) },')
one('            text = { Text(when (kind) {\n                CodexSafetyConfirmation.CRITICAL -> "Full access + Never removes the normal sandbox restriction while also disabling approval prompts. Codex may modify data available in its execution environment without asking."\n                CodexSafetyConfirmation.FULL_ACCESS -> "Sandbox restrictions are removed. Codex may modify data available inside its execution environment. Enable only when you intentionally want unrestricted execution."\n                else -> "Approval prompts are disabled. Operations blocked by the sandbox or policy may fail rather than ask. This does not itself mean Full access."\n            }) },', '            text = { Text(if (japanese) when (kind) {\n                CodexSafetyConfirmation.CRITICAL -> "「フルアクセス」+「承認を求めない」は通常のサンドボックス制限を解除し、承認確認も無効にします。Codexは実行環境からアクセス可能なデータを確認なしで変更できる可能性があります。"\n                CodexSafetyConfirmation.FULL_ACCESS -> "サンドボックス制限が解除されます。Codexは実行環境内のデータを変更できる可能性があります。制限のない実行を意図している場合のみ有効にしてください。"\n                else -> "承認確認が無効になります。サンドボックスやポリシーで禁止された操作は確認を求めず失敗する場合があります。これだけでフルアクセスになるわけではありません。"\n            } else when (kind) {\n                CodexSafetyConfirmation.CRITICAL -> "Full access + Never removes the normal sandbox restriction while also disabling approval prompts. Codex may modify data available in its execution environment without asking."\n                CodexSafetyConfirmation.FULL_ACCESS -> "Sandbox restrictions are removed. Codex may modify data available inside its execution environment. Enable only when you intentionally want unrestricted execution."\n                else -> "Approval prompts are disabled. Operations blocked by the sandbox or policy may fail rather than ask. This does not itself mean Full access."\n            }) },')
one('        Text(title, style = MaterialTheme.typography.titleMedium)', '        Text(codexUiText(title), style = MaterialTheme.typography.titleMedium)')

insert = '''\nprivate fun localizedTurnWireStatus(value: String): String = when (value) {\n    "completed" -> "完了"\n    "interrupted" -> "中断"\n    "failed" -> "失敗"\n    "inProgress" -> "実行中"\n    else -> value\n}\n\nprivate fun localizedTurnStatusSummary(value: String): String = value\n    .replace("Completed", "完了")\n    .replace("Interrupted", "中断")\n    .replace("Failed", "失敗")\n    .replace("In progress", "実行中")\n    .replace(" min ", "分 ")\n    .replace(" s", "秒")\n\nprivate fun localizedErrorCategory(value: String): String = when (value) {\n    "Codex error" -> "Codex エラー"\n    "Other Codex error" -> "その他の Codex エラー"\n    else -> value\n}\n'''
marker = '\nprivate fun CodexConversationUiState.telemetryOrNull()'
if marker not in text:
    raise SystemExit("helper insertion marker missing")
text = text.replace(marker, insert + marker, 1)
p.write_text(text)
